version: '3.8'

volumes:
  postgres:

services:
  php:
    build: ./docker/php
    environment:
      XHPROF_ENABLE: '${XHPROF_ENABLE:-0}'
      XDEBUG_MODE: debug
      XDEBUG_SESSION: PHPSTORM
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www
  nginx:
    image: nginx:alpine
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: lessons
      POSTGRES_TEST_DB: lessons_test
      # You should definitely change the password in production
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker/create_test_postgres_db.sh:/docker-entrypoint-initdb.d/create_test_postgres_db.sh